# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1608955734a2a8f0f89e1cfa95a11b12ecd4b4e41d8b5c5daac16b87da0b215a45a77726df723c94612692e6c10a47e07758624b217141f3a8f9b966b203f852

test:
  secret_key_base: 523c0954c3a980c6ca68fb3be4ff527889ece65d0570d3df538383571aa69a100132a686edc4131470207e390e4625b7b57aa76c80daab9118c9e935881686ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
